### ISSUE TITLE
VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by Roundtree-Larry** [mrdavey/ez-flashloan#5]
any solution please:

truffle(development)> await f.flashloan()
Thrown:
Error: Returned error: VM Exception while processing transaction: revert
    at evalmachine.<anonymous>:1:11
    at evalmachine.<anonymous>:2:49
    at sigintHandlersWrap (vm.js:269:15)
    at Script.runInContext (vm.js:124:14)
    at runScript (C:\Users\\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:222:1)
    at Console.interpret (C:\Users\\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:237:1)
    at ReplManager.interpret (C:\Users\\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\repl.js:129:1)
    at bound (domain.js:419:14)
    at REPLServer.runBound [as eval] (domain.js:432:12)
    at REPLServer.onLine (repl.js:716:10)
    at REPLServer.emit (events.js:223:5)
    at REPLServer.EventEmitter.emit (domain.js:475:20)
    at REPLServer.Interface._onLine (readline.js:315:10)
    at REPLServer.Interface._line (readline.js:692:8)
    at REPLServer.Interface._ttyWrite (readline.js:1017:14)
    at REPLServer.self._ttyWrite (repl.js:793:7)
    at ReadStream.onkeypress (readline.js:191:10)
    at ReadStream.emit (events.js:223:5)
    at ReadStream.EventEmitter.emit (domain.js:475:20)
    at emitKeys (internal/readline/utils.js:433:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1151:36)
    at ReadStream.emit (events.js:223:5)
    at ReadStream.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11) {
  hijackedStack: 'Error: Returned error: VM Exception while processing transaction: revert\n' +
    '    at Object.ErrorResponse (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-core-helpers\\src\\errors.js:29:1)\n' +
    '    at C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-core-requestmanager\\src\\index.js:140:1\n' +
    '    at C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\packages\\provider\\wrapper.js:112:1\n' +
    '    at XMLHttpRequest.request.onreadystatechange (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-providers-http\\src\\index.js:96:1)\n' +
    '    at XMLHttpRequestEventTarget.dispatchEvent (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request-event-target.js:34:1)\n' +
    '    at XMLHttpRequest._setReadyState (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request.js:208:1)\n' +
    '    at XMLHttpRequest._onHttpResponseEnd (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request.js:318:1)\n' +
    '    at IncomingMessage.<anonymous> (C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request.js:289:47)\n' +
    '    at IncomingMessage.emit (events.js:228:7)\n' +
    '    at IncomingMessage.EventEmitter.emit (domain.js:498:23)\n' +
    '    at endReadableNT (_stream_readable.js:1185:12)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:81:21)'
}

**Comment by Roundtree-Larry** [comment]
btw the command: let f = await Flashloan.deployed()
give me : undefine
